apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: consent-soe
  namespace: demo-services
spec:
  encryptedData:
    application.yaml: AgBYGilHnHC3sS2rGwum1z7t02wd13T2gPB/U4vbKkKOJetlWPkaWWMt1Z58ZOhKym6xotE+a0CYUTm2CIj8ENf3JYRAq4TKkg+p+rs3Q1LJhAF6LQePFoVBjE2TNY0a6JFu19YiaIG2LvMP1Qjrxr5TLHlR9tQjlardlZ8HSzFGoywsai2YwJz3405K/R91E5zOXE1ERhsX0GONoLbcmyxZPofpvYG36ZPljQDpYCqjzvlQbDhZAmCcqqf6qx7+UcvXIcDNuBOo1WgdfnsN2y1ePb4hmD1bHX9+o5u8L5am0usfeBZ1C3xXXQK23f46XWEWhh3WkBHjmsm2VGVtN4gbTE519aUfZMIO37egeCeQHoUBA9vs8GaG+9AGXNoyDSTbaWuC0qemFmCs5m9qeSXuebprkKLuTslEJ4UIer0MWGBU0Vb+pzFIdEKQE55BPZ1V+tFAdCw0eijaZakVjMuVS22SliTwRNUE07cMCaiOG5gKjQtb/vt5Os5avIidXk3Y/R5WBiIJk/aSw5KeTtoaRvaRhZPG8vtJ41kjSYbw8hx1A1HZ/AQivIyy6M9RFAOxWovUJDl3561lukuIoKeSzfQeGS2EL0K9OzP9M1eDhNwL13dgR5yM98KtwCU6N+vk05RIDLEbSmyvqtg6dh4NQzN9oIzx06iJIiAybJk0TC9Dbrlqn6f1ujRUv1XqnpHWmga0mP5BpwEJ70y+zod2jOGReOsrYHXfximowzVV3ciIF0Zyd5/5kTtt68XCmSTzoNntojhcGbTk7w5i+/+17kR+ZzPhaHcggXT9ayru4iV+bnYtTekWc11Sf1lOQ5UqQdT7r0lRsGB0U5Sw4AOFeKgV9oOB6rmH4l2F59ZNb6wEYQD5TXtHUI2s2/H7J/rdim2p9POBWLcOcUhN31Cj/p6GHb+XkmCwlqsOZOP9q2kpLYsx7IgOZr2FJo464JFJiSiNCYXd1QULZUdKDAYu3uaGbw8nI9jmuwR++181etgPbZqNqh/cQjynY90kP83gsOVbBN7uSUS4HagX2bwWp2kTjczHL3MlVeQFjLj8fMo2pJcB49XrMlXOzxpHDJ0pwvDwhatPio7+bBMRkUiTAMrXNN9Hr4Cmx8I200JwBxbAs/eM9KoY6fGvUtH/ZvdIgJ/rNaVAbjBHem6e57DAfCEumzDytHmFAxrmaSp1NhHVAjXUv236znQ2nsaLAZEDEiQLPZ2B2oW2TgmI4qcTm1LRaYg4/b1NwAmEBCbhahuMDFS8X9wVaTp95IWsDfKolCEYSIa/XczYMsCfSuNyz3QNlI81nzYew8uG8694+uAR12RIu56fWPcmYPci42mnhC0QKI7bLSjGWt3ZINq7Hsd8pmvmEXDl2QtiIV6GTEB5hk97LnTorYk6VoipsyTsgEpNoYZXn1looOESfvrh6XxPcsXaGader3UdlUU96DT/OMtnBWRVI26Fws46Jfk/SBvKflHJn75XOG1vvGLVn5doxamiopjZEOy/V3n5f8gX/Lg=
  template:
    metadata:
      creationTimestamp: null
      name: consent-soe
      namespace: demo-services

