apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: consent-demo-soe
  namespace: demo-services
spec:
  interval: 5m
  chart:
    spec:
      chart: demo-soe
      version: '1.x.x'
      sourceRef:
        kind: HelmRepository
        name: demo-system-helm
        namespace: flux-system
      interval: 5m
  values:
    demo:
      verticalName: consent

    configSecretName: consent-soe
    caCertsConfigMapName: java-truststore

    repository:
      host: gitlab.codecentric.de:4567
      path: demo-system-platform-team/demo-platform

    image:
      name: consent-soe
      tag: 1.2.10 # version marker for: consent-soe
      pullPolicy: IfNotPresent

    imagePullSecrets:
      - name: gitlab-pull-secret

    podSecurityPolicy:
      create: true

    jvm:
      options: >
        -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=50
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
        -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010
        -Dcom.sun.management.jmxremote.rmi.port=9010 -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.ssl=false
        -Djava.rmi.server.hostname=127.0.0.1

    resources:
      requests:
        cpu: 100m
        memory: 768Mi
      limits:
        cpu: 2
        memory: 1200Mi

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: traefik-ingress
        ingress.kubernetes.io/custom-request-headers: l5d-dst-override:consent-demo-soe.demo-services.svc.cluster.local:8080
      hosts:
        - host: consent-demo-platform.demo-system.codecentric.cloud
          paths:
            - "/"
      tls:
        - hosts:
            - consent-demo-platform.demo-system.codecentric.cloud
          secretName: consent-soe-cert

    kafka:
      clusterCaSecretName: "cluster-cluster-ca-cert"
      userSecretName: "consent-soe-user"
