apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: consent-demo-sor
  namespace: demo-services
spec:
  interval: 5m
  chart:
    spec:
      chart: demo-sor
      version: '1.x.x'
      sourceRef:
        kind: HelmRepository
        name: demo-system-helm
        namespace: flux-system
      interval: 5m
  values:
    demo:
      verticalName: consent

    configSecretName: consent-sor
    caCertsConfigMapName: java-truststore

    repository:
      host: gitlab.codecentric.de:4567
      path: demo-system-platform-team/demo-platform

    image:
      name: consent-sor
      tag: 1.2.8 # version marker for: consent-sor
      pullPolicy: IfNotPresent

    imagePullSecrets:
      - name: gitlab-pull-secret

    podSecurityPolicy:
      create: true

    jvm:
      options: >
        -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=50
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
        -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010
        -Dcom.sun.management.jmxremote.rmi.port=9010 -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.ssl=false
        -Djava.rmi.server.hostname=127.0.0.1

    resources:
      requests:
        cpu: 100m
        memory: 600Mi
      limits:
        cpu: 2
        memory: 1Gi

    kafka:
      clusterCaSecretName: "cluster-cluster-ca-cert"
      userSecretName: "consent-sor-user"
