apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-container-pipeline
spec:
  workspaces:
    - name: build-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: build-workspace
      params:
        - name: url
          value: https://github.com/marcopaga/feeding-the-ci-process-single-dockerfile.git
        - name: deleteExisting
          value: "true"
    - name: build
      taskRef:
        name: buildpacks
      runAfter:
        - fetch-repository
      params:
        - name: APP_IMAGE
          value: k3d-registry.localhost:5000/creator:latest
        - name: BUILDER_IMAGE
          value: gcr.io/buildpacks/builder:v1
      workspaces:
        - name: source
          workspace: build-workspace
