apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: strimzi
  namespace: demo-kafka
spec:
  interval: 5m
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: '0.19.0'
      sourceRef:
        kind: HelmRepository
        name: strimzi
        namespace: flux-system
      interval: 1m
  values:
    watchAnyNamespace: true
