apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  interval: 5m
  chart:
    spec:
      chart: keda
      version: '2.4.0'
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: flux-system
      interval: 1m