apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keycloak
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keycloak-psp-clusterrole
subjects:
  - kind: ServiceAccount
    name: default
    namespace: demo-keycloak
