apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloak-psp-clusterrole
rules:
  - apiGroups:
      - extensions
    resourceNames:
      - keycloak
    resources:
      - podsecuritypolicies
    verbs:
      - use
