apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: demo-keycloak
data:
  end-user-realm.json: |
    {
      "id": "demo-users",
      "realm": "demo-users",
      "enabled": true,
      "sslRequired": "external",
      "registrationAllowed": false,
      "registrationEmailAsUsername": false,
      "rememberMe": false,
      "verifyEmail": false,
      "loginWithEmailAllowed": true,
      "duplicateEmailsAllowed": false,
      "resetPasswordAllowed": false,
      "editUsernameAllowed": false,
      "bruteForceProtected": false,
      "permanentLockout": false,
      "users": [
      {
        "username": "user",
        "enabled": true,
        "email": "user@example.org",
        "firstName": "User",
        "lastName": "User",
        "credentials": [
        {
          "type": "password",
          "value": "user"
        }
        ],
        "attributes": {
          "onlineId": "9561000000000001803677"
        }
      }
      ],
      "requiredCredentials": [
        "password"
      ],
      "clients": [
      {
        "clientId": "demo",
        "baseUrl": "",
        "enabled": true,
        "clientAuthenticatorType": "client-secret",
        "implicitFlowEnabled": true,
        "secret": "**********",
        "redirectUris": [
          "http://localhost:8080/",
          "http://localhost:3000/"
        ],
        "protocol": "openid-connect",
        "protocolMappers": [
        {
          "id": "509aeece-3551-4753-a539-88cba7e38f1d",
          "name": "onlineIdMapper",
          "protocol": "openid-connect",
          "protocolMapper": "oidc-usermodel-attribute-mapper",
          "consentRequired": false,
          "config": {
            "user.attribute": "onlineId",
            "id.token.claim": "true",
            "access.token.claim": "true",
            "claim.name": "demo_onlineid",
            "userinfo.token.claim": "true"
          }
        }
        ]
      }
      ]
    }
  technical-user-realm.json: |
    {
      "id": "demo-services",
      "realm": "demo-services",
      "enabled": true,
      "sslRequired": "external",
      "registrationAllowed": false,
      "registrationEmailAsUsername": false,
      "rememberMe": false,
      "verifyEmail": false,
      "loginWithEmailAllowed": true,
      "duplicateEmailsAllowed": false,
      "resetPasswordAllowed": false,
      "editUsernameAllowed": false,
      "bruteForceProtected": false,
      "permanentLockout": false,
      "requiredCredentials": [
        "password"
      ],
      "clients": [
        {
          "clientId": "demo",
          "baseUrl": "",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "secret": "**********",
          "protocol": "openid-connect",
          "serviceAccountsEnabled": true,
          "standardFlowEnabled": false,
          "protocolMappers": [
            {
              "id": "e668d6ac-03ba-48c9-921d-ef5689925dda",
              "name": "service-id-mapper",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usersessionmodel-note-mapper",
              "consentRequired": false,
              "config": {
                "user.session.note": "clientId",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "demo_service_id",
                "jsonType.label": "String"
              }
            }
          ]
        }
      ]
    }