apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: soe-metrics
  namespace: demo-services
  labels:
    release: prometheus-operator # only on our cluster
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: soe
  namespaceSelector:
    matchNames:
      - demo-services
  podMetricsEndpoints:
    - path: /actuator/prometheus
      port: http
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sor-metrics
  namespace: demo-services
  labels:
    release: prometheus-operator # only on our cluster
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: sor
  namespaceSelector:
    matchNames:
      - demo-services
  podMetricsEndpoints:
    - path: /actuator/prometheus
      port: http
