apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-redis-secret
  namespace: default
spec:
  secretTargetRef:
  - parameter: password
    name: redis
    key: redis-password
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redis-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: worker
  minReplicaCount: 0
  maxReplicaCount: 5
  pollingInterval: 10
  cooldownPeriod: 30
  triggers:
  - type: redis
    metadata:
      address: redis-master.default:6379
      listName: test-queue
      listLength: "10"
    authenticationRef:
      name: keda-trigger-auth-redis-secret
