apiVersion: apps/v1
kind: Deployment
metadata:
  name: creator
spec:
  selector:
    matchLabels:
      app: creator
  template:
    metadata:
      labels:
        app: creator
    spec:
      containers:
      - name: creator
        image: k3d-registry.localhost:5000/creator:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: REDIS_SERVICE_HOST
          value: "redis-master"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: k3d-registry.localhost:5000/worker:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: REDIS_SERVICE_HOST
          value: "redis-master"