apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitnami
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: '6.2.5'
      sourceRef:
        kind: HelmRepository
        name: redis
        namespace: default
      interval: 1m