name: create-cluster

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install K3d (see https://k3d.io/#installation) & flux & Tekton CLI
        run: |
          brew install fluxcd/tap/flux
          brew install k3d
          brew tap tektoncd/tools
          brew install tektoncd/tools/tektoncd-cli

      - name: Bootstrap k3d
        run: |
          k3d registry create registry.localhost --port 5000
          k3d cluster create --registry-use k3d-registry.localhost:5000

      # See creation of Personal Access Token at https://fluxcd.io/docs/cmd/flux_bootstrap_github/
      - name: Install Flux into K3d cluster & connect to GitHub repository https://github.com/marcopaga/tekton-demo
        run: |
          GITHUB_USER=marcopaga GITHUB_TOKEN=${{ secrets.FLUX_GITHUB_TOKEN }} flux bootstrap github \
          --owner=marcopaga \
          --repository=tekton-demo \
          --private=false \
          --personal=true \
          --branch=main \
          --path=clusters/local

      - name: Run Tekton build
        run: |
          tkn task list
          tkn pipeline list