name: create-cluster

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install K3d (see https://k3d.io/#installation) & flux
        run: |
          brew install fluxcd/tap/flux
          brew install k3d

      - name: Bootstrap k3d
        run: |
          k3d registry create registry.localhost --port 5000
          k3d cluster create --registry-use k3d-registry.localhost:5000

      - name: Install Flux into K3d cluster & connect to GitHub repository https://github.com/marcopaga/tekton-demo
        run: |
          GITHUB_USER=${{ github.actor }} GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} flux bootstrap github \
          --owner=${{ github.actor }} \
          --repository=tekton-demo \
          --private=false \
          --personal=true \
          --branch=main \
          --path=clusters/local
