name: create-cluster

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install K3d (see https://k3d.io/#installation) & flux & Tekton CLI
        run: |
          brew install fluxcd/tap/flux
          brew install k3d
          brew tap tektoncd/tools
          brew install tektoncd/tools/tektoncd-cli

      - name: Bootstrap k3d
        run: |
          k3d registry create registry.localhost --port 5000
          k3d cluster create --registry-use k3d-registry.localhost:5000

      # See creation of Personal Access Token at https://fluxcd.io/docs/cmd/flux_bootstrap_github/
      - name: Install Flux into K3d cluster & connect to GitHub repository https://github.com/marcopaga/tekton-demo
        run: |
          GITHUB_USER=marcopaga GITHUB_TOKEN=${{ secrets.FLUX_GITHUB_TOKEN }} flux bootstrap github \
          --owner=marcopaga \
          --repository=tekton-demo \
          --private=false \
          --personal=true \
          --branch=main \
          --path=clusters/local

      - name: Wait for CRD Deployment
        timeout-minutes: 3
        continue-on-error: true
        run: |
          { grep -q -m 1 "pipelines.tekton.dev"; kill $!; } < <(kubectl get crd -w)
          kubectl -n default wait --for condition=established --timeout=180s crd/pipelines.tekton.dev

      - name: Introspection
        run: |
          kubectl get namespaces
          kubectl get pods --all-namespaces
          kubectl get deployments --all-namespaces
          kubectl get Kustomization -n flux-system

      - name: Check Tekton tasks and pipelines
        run: |
          tkn task list
          tkn pipeline list

      - name: Execute pipeline
        run: |
          kubectl create -f ./pipeline-run.yaml
          tkn pipelinerun list
